### ISSUE TITLE
Events are not chronological

### ISSUE THREAD

**Issue by 0xrb** [gutechsoc/gutechsoc.github.io#17]
@ /#events

CDX2019 is at the top of the list, instead of its true chronological order.

**Comment by gdcodes** [comment]
The events were in the correct order but the year of our recent CDX event was incorrectly typed (2019 instead of 2020). I am sorry for the error. This has now been fixed and an image from the event has been used to replace the initial placeholder in the Events section.

**Comment by 0xrb** [comment]
Hi Gloria thanks for doing that. But what about CDX2019?

**Comment by gdcodes** [comment]
I think that's where the problem started - I started working on the website much later so I made the mistake of assuming that the events prior to me joining were updated. Sorry about that, I'll add the information for 2019 now.

**Comment by 0xrb** [comment]
Sorry! I didn't realise we were talking about different events haha, glad that's clear now.

**Comment by gdcodes** [comment]
No worries! I have pushed the changes for CDX 2019 related content including photos from the event. Also the past events list should be in the correct order now.
